apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage
  labels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: idp-platform
data:
  app-config.yaml: |
    # This will be mounted as a volume
    # The actual app-config.yaml content will be injected here
    # or mounted from a separate ConfigMap/Secret