apiVersion: v1
kind: ServiceAccount
metadata:
  name: backstage-backend
  namespace: backstage
  labels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: idp-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backstage-backend-reader
  labels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: idp-platform
rules:
# Kubernetes plugin permissions
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "limitranges"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
  verbs: ["get", "list"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backstage-backend-reader
  labels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: idp-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backstage-backend-reader
subjects:
- kind: ServiceAccount
  name: backstage-backend
  namespace: backstage